### ISSUE TITLE
Render thread/WARN 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [MehVahdJukaar/AdvancementFrames#21]
advancementframes-1.19.2-2.0.0.jar
Could this be related to your mod? I'm looking for a mistake. I have 3000 such messages in the log.

[19:52:56] [Render thread/WARN]: Told to remove advancement dnl:util/entity_hit_matching/using_shield but I don't know what that is
17746 | [19:52:56] [Render thread/INFO]: Loaded 325 advancements

**Comment by MehVahdJukaar** [comment]
dont think so

**Comment by Krimatoria** [comment]
> не думаю так

ok)
