### ISSUE TITLE
Registry Object not present: advancementframes:advancement_frame

### ISSUE THREAD

**Issue by C1ffisme** [MehVahdJukaar/AdvancementFrames#6]
Crash log: https://paste.ee/p/btUQB

Happens on startup using the latest version of Forge 1.18.2

**Comment by MehVahdJukaar** [comment]
You are not using 1.18.2 version. In fact you aren't even using latest 1.18.1 version

**Comment by C1ffisme** [comment]
Sorry, must have deleted the wrong file when redownloading mods
